baseURL = "/"
title = "Kokabieli"
theme = "hugo-geekdoc"

pluralizeListTitles = false

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"


[params]
geekdocToC = 3
geekdocLogo = "brand.svg"
geekdocCollapseAllSections = true
geekdocRepo = "https://github.com/kokabieli/kokabieli.github.io"
geekdocEditPath = "edit/main"
geekdocAnchor = true
geekdocAnchorCopy = true
